exec: {}
in:
  type: sfdc_event_log_files
  oauth:
    id: oauth_id
    secret: oauth_secret
  username: nahi@treasure-data.com
  password: password+securityToken
  schema:
    - { name: time, type: long }
    - { name: ACTION, type: string }
    - { name: API_TYPE, type: string }
    - { name: API_VERSION, type: string }
    - { name: APP_NAME, type: string }
    - { name: APP_TYPE, type: string }
    - { name: BATCH_ID, type: string }
    - { name: BROWSER_NAME, type: string }
    - { name: BROWSER_TYPE, type: string }
    - { name: BROWSER_VERSION, type: string }
    - { name: CARRIER, type: string }
    - { name: CHANGE_SET_NAME, type: string }
    - { name: CLASS_NAME, type: string }
    - { name: CLIENT, type: string }
    - { name: CLIENT_ID, type: string }
    - { name: CLIENT_INFO, type: string }
    - { name: CLIENT_IP, type: string }
    - { name: CLIENT_NAME, type: string }
    - { name: CLIENT_VERSION, type: string }
    - { name: CONNECTION_TYPE, type: string }
    - { name: CONTROLLER_TYPE, type: string }
    - { name: CURRENT_SANDBOX_ORG_ID, type: string }
    - { name: DASHBOARD_COMPONENT_ID, type: string }
    - { name: DASHBOARD_ID, type: string }
    - { name: DASHBOARD_TYPE, type: string }
    - { name: DATA, type: string }
    - { name: DELEGATED_USER_ID, type: string }
    - { name: DELEGATED_USER_NAME, type: string }
    - { name: DELIVERY_ID, type: string }
    - { name: DELIVERY_LOCATION, type: string }
    - { name: DEVICE_ID, type: string }
    - { name: DISPLAY_TYPE, type: string }
    - { name: DOCUMENT_ID, type: string }
    - { name: ENTITY_ID, type: string }
    - { name: ENTITY_NAME, type: string }
    - { name: ENTITY_TYPE, type: string }
    - { name: ENTRY_POINT, type: string }
    - { name: EVENT_TYPE, type: string }
    - { name: FAILURE_TYPE, type: string }
    - { name: FILE_NAME, type: string }
    - { name: FILE_PREVIEW_TYPE, type: string }
    - { name: FILE_TYPE, type: string }
    - { name: HAS_CHART, type: string }
    - { name: HTTP_HEADERS, type: string }
    - { name: HTTP_METHOD, type: string }
    - { name: IS_AJAX_REQUEST, type: string }
    - { name: IS_API, type: string }
    - { name: IS_ERROR, type: string }
    - { name: IS_FIRST_REQUEST, type: string }
    - { name: IS_GUEST, type: string }
    - { name: IS_MANAGED, type: string }
    - { name: IS_PUSH, type: string }
    - { name: IS_RELEASED, type: string }
    - { name: IS_SCHEDULED, type: string }
    - { name: IS_SECURE, type: string }
    - { name: IS_SUCCESS, type: string }
    - { name: IS_SUCCESSFUL, type: string }
    - { name: JOB_ID, type: string }
    - { name: LIMIT_USAGE_PERCENT, type: string }
    - { name: LOCATION, type: string }
    - { name: LOG_GROUP_ID, type: string }
    - { name: MANAGED_PACKAGE_NAMESPACE, type: string }
    - { name: MASTER_REPORT_ID, type: string }
    - { name: MEDIA_TYPE, type: string }
    - { name: MESSAGE, type: string }
    - { name: METHOD, type: string }
    - { name: METHOD_NAME, type: string }
    - { name: NETWORK_ID, type: string }
    - { name: NUMBER_BUCKETS, type: string }
    - { name: NUMBER_COLUMNS, type: string }
    - { name: NUMBER_EXCEPTION_FILTERS, type: string }
    - { name: NUMBER_FAILURES, type: string }
    - { name: NUMBER_FIELDS, type: string }
    - { name: NUMBER_OF_RECORDS, type: string }
    - { name: NUMBER_SOQL_QUERIES, type: string }
    - { name: NUMBER1, type: string }
    - { name: NUMBER2, type: string }
    - { name: OBJECT_TYPE, type: string }
    - { name: OPERATION, type: string }
    - { name: OPERATION_TYPE, type: string }
    - { name: ORGANIZATION_ID, type: string }
    - { name: OS_NAME, type: string }
    - { name: OS_VERSION, type: string }
    - { name: PACKAGE_NAME, type: string }
    - { name: PAGE_NAME, type: string }
    - { name: PENDING_SANDBOX_ORG_ID, type: string }
    - { name: PLATFORM_TYPE, type: string }
    - { name: QUERY, type: string }
    - { name: RECORD_ID, type: string }
    - { name: REFERRER, type: string }
    - { name: REFERRER_URI, type: string }
    - { name: RELATED_ENTITY_ID, type: string }
    - { name: RENDERING_TYPE, type: string }
    - { name: REPORT_DESCRIPTION, type: string }
    - { name: REPORT_ID, type: string }
    - { name: REQUEST_ID, type: string }
    - { name: REQUEST_METHOD, type: string }
    - { name: REQUEST_SIZE, type: string }
    - { name: REQUEST_STATUS, type: string }
    - { name: REQUEST_TYPE, type: string }
    - { name: RESOLUTION_TYPE, type: string }
    - { name: RESPONSE_SIZE, type: string }
    - { name: ROWS_PROCESSED, type: string }
    - { name: RUN_TIME, type: string }
    - { name: SANDBOX_ID, type: string }
    - { name: SDK_APP_NAME, type: string }
    - { name: SDK_APP_TYPE, type: string }
    - { name: SDK_APP_VERSION, type: string }
    - { name: SDK_MODEL, type: string }
    - { name: SDK_VERSION, type: string }
    - { name: SESSION_ID, type: string }
    - { name: SESSION_LEVEL, type: string }
    - { name: SESSION_TYPE, type: string }
    - { name: SHARED_WITH_ENTITY_ID, type: string }
    - { name: SHARING_OPERATION, type: string }
    - { name: SHARING_PERMISSION, type: string }
    - { name: SIGNAL_STRENGTH, type: string }
    - { name: SITE_ID, type: string }
    - { name: SIZE_BYTES, type: string }
    - { name: SORT, type: string }
    - { name: SOURCE_IP, type: string }
    - { name: STATUS, type: string }
    - { name: STATUS_CODE, type: string }
    - { name: SUCCESS, type: string }
    - { name: TARGET, type: string }
    - { name: TARGET_ORG_ID, type: string }
    - { name: TARGET2, type: string }
    - { name: TIMESTAMP, type: string }
    - { name: TRANSACTION_TYPE, type: string }
    - { name: TRIGGER_ID, type: string }
    - { name: TRIGGER_NAME, type: string }
    - { name: TRIGGER_TYPE, type: string }
    - { name: TYPE, type: string }
    - { name: URI, type: string }
    - { name: URL, type: string }
    - { name: USAGE_TIMESTAMP, type: string }
    - { name: USER_AGENT, type: string }
    - { name: USER_ID, type: string }
    - { name: USER_INITIATED_LOGOUT, type: string }
    - { name: USER_NAME, type: string }
    - { name: USER_TYPE, type: string }
    - { name: VERSION_ID, type: string }
    - { name: VIEW_STATE_SIZE, type: string }
out: {type: stdout}
